SELECT  RUA.TLO_TX as TIPO_LOGRADOURO,
	   (RUA.TLO_TX & ' ' & RUA.LOG_NO & ' ' & RUA.LOG_COMPLEMENTO) as LOGRADOURO_COMPLETO,
	   (RUA.TLO_TX & ' ' & RUA.LOG_NO) as LOGRADOURO,
	    RUA.LOG_COMPLEMENTO as COMPLEMENTO, 
	   (IIF(RUA.LOG_COMPLEMENTO IS NULL, NULL, (IIF(NUMSEQ.SEC_NU_INI = '1', 'Até ', IIF(NUMSEQ.SEC_NU_INI = '2', 'Até ', (NUMSEQ.SEC_NU_INI & ' à '))) &  
	   NUMSEQ.SEC_NU_FIM & ' - ' & 
	   IIF(NUMSEQ.SEC_IN_LADO = 'P', 'PAR', IIF(NUMSEQ.SEC_IN_LADO = 'I', 'IMPAR', 'AMBOS'))))) as COMPLEMENTO_COMPLETO,
       BAIRRO.BAI_NO as BAIRRO,
       CIDADE.LOC_NO as CIDADE,
       BAIRRO.UFE_SG as UF,
       RUA.CEP as CEP
FROM (((LOG_LOGRADOURO as RUA INNER JOIN  LOG_BAIRRO as BAIRRO ON RUA.BAI_NU_INI = BAIRRO.BAI_NU)
     	INNER JOIN LOG_LOCALIDADE as CIDADE ON RUA.LOC_NU = CIDADE.LOC_NU)  
     	LEFT JOIN LOG_NUM_SEC as NUMSEQ ON RUA.LOG_NU = NUMSEQ.LOG_NU)   
WHERE 
RUA.CEP LIKE '32600312'
 
 
 
 
 
SELECT  RUA.TLO_TX as TIPO_LOGRADOURO,
	   (RUA.TLO_TX & ' ' & RUA.LOG_NO & ' ' & RUA.LOG_COMPLEMENTO) as LOGRADOURO_COMPLETO,
	   (RUA.TLO_TX & ' ' & RUA.LOG_NO) as LOGRADOURO,
	    RUA.LOG_COMPLEMENTO as COMPLEMENTO, 
	   (IIF(RUA.LOG_COMPLEMENTO IS NULL, NULL, (IIF(NUMSEQ.SEC_NU_INI = '1', 'Até ', IIF(NUMSEQ.SEC_NU_INI = '2', 'Até ', (NUMSEQ.SEC_NU_INI & ' à '))) &  
	   NUMSEQ.SEC_NU_FIM & ' - ' & 
	   IIF(NUMSEQ.SEC_IN_LADO = 'P', 'PAR', IIF(NUMSEQ.SEC_IN_LADO = 'I', 'IMPAR', 'AMBOS'))))) as COMPLEMENTO_COMPLETO,
       BAIRRO.BAI_NO as BAIRRO,
       CIDADE.LOC_NO as CIDADE,
       BAIRRO.UFE_SG as UF,
       RUA.CEP as CEP
FROM (((LOG_LOGRADOURO as RUA INNER JOIN  LOG_BAIRRO as BAIRRO ON RUA.BAI_NU_INI = BAIRRO.BAI_NU)
     	INNER JOIN LOG_LOCALIDADE as CIDADE ON RUA.LOC_NU = CIDADE.LOC_NU)  
     	LEFT JOIN LOG_NUM_SEC as NUMSEQ ON RUA.LOG_NU = NUMSEQ.LOG_NU)   
WHERE 
(RUA.TLO_TX & ' ' & RUA.LOG_NO) LIKE 'Rua Tapajós'